# _quarto.yml
project:
  type: website
  resources:
    - "projects/**"

website:
  title: ""

format:
  html:
    theme: none
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
    include-after-body:
      - file: scripts.html
